services:
  frontend:
    image: spanishhans/twatter_frnt:0.1.1
    container_name: twatter_frnt
    ports:
      - "10311:3000"
    networks:
      - app_net
    environment:
      GATEWAY_URL: "http://frontend-gateway:8080"
    # depends_on:
    #   - frontend-gateway

  # frontend-gateway:
  #   image: nginx:latest
  #   container_name: twatter_nginx
  #   ports:
  #     - "10312:8080"
  #   volumes:
  #     - ./nginx_confs:/etc/nginx
  #   networks:
  #     - app_net
    # depends_on:
    #   - posts
    #   - auth
    #   - interactions

  # posts:
  #   build: ./pubs
  #   container_name: twatter_pubs
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
  #   depends_on:
  #     - db
  
  # auth:
  #   build: ./auth
  #   container_name: twatter_auth
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
  #   depends_on:
  #     - db

  # interactions:
  #   build: ./ints
  #   container_name: twatter_ints
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}"
  #   depends_on:
  #     - db
  
  db:
    image: postgres:16
    env_file: ./.env
    container_name: twatter_db
    networks:
      - app_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    env_file: ./.env
    container_name: twatter_pgadmin
    ports:
      - "10313:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - ./pgadmin:/var/lib/pgadmin

networks:
  app_net:
    driver: bridge
    name: twatter_network
