version: '3.8'

services:
  
  # frontend:
  #   build: ./frnt
  #   ports:
  #     - "10311:3000"
  #   networks:
  #     - app_net
  #   environment:
  #     GATEWAY_URL: "http://frontend-gateway:8080"
  #   depends_on:
  #     - frontend-gateway

  
  # frontend-gateway:
  #   image: nginx:latest
  #   ports:
  #     - "10312:8080"
  #   volumes:
  #     - ./nginx/frontend-gateway.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - app_net
  #   depends_on:
  #     - posts
  #     - auth
  #     - interactions

  
  # posts:
  #   build: ./pubs
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/twitter_db"
  #   depends_on:
  #     - db

  
  # auth:
  #   build: ./auth
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/twitter_db"
  #   depends_on:
  #     - db

  
  # interactions:
  #   build: ./ints
  #   networks:
  #     - app_net
  #   environment:
  #     DATABASE_URL: "postgresql://${DB_USER}:${DB_PASS}@db:5432/twitter_db"
  #   depends_on:
  #     - db

  
  db:
    image: postgres:16
    networks:
      - app_net
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: twitter_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      retries: 5
      timeout: 3s
      
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "10313:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASS}
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

networks:
  app_net:
    driver: bridge
    name: twatter_network
